## Setup
title:            Guilherme Cardoso
tagline:          'Software Programmer'
description:      'My personal website and blog.'
url:              http://guilhermecardoso.pt
name: 'Guilherme Cardoso'
comments: true
gems:
  - jekyll-sitemap
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'