## Setup
title:            Codigo
tagline:          'Software Programmer'
description:      'Codigo'
url:              http://www.codigo.ovh
name: 'Codigo'
comments: true
gems:
  - jekyll-sitemap
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'