## Setup
title:            Guilherme Cardoso
tagline:          'Software Programmer'
description:      'My personal website and blog.'
url:              http://guilhermegeek.github.io
name: 'Gui'
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'